### ISSUE TITLE
Self-play code/hyperparameters

### ISSUE THREAD

**Issue by Omegastick** [Miffyli/ToriLLE#3]
In the paper on Arxiv you talk about your experiment with self-play, but I can't find the self-play code or hyperparameters in the experiments folder. Are they available?

**Comment by Miffyli** [comment]
Originally I did not include the self-play experiment code as they were messy beyond any recognition. However I now have bit cleaner code with original hyperparameters (and flaws) which I can share. I am currently away from my workstation and it may take a week before I will add it here.

**Comment by Omegastick** [comment]
Okay, thanks very much.

**Comment by Miffyli** [comment]
I have now added self-play experiment code [under experiments](https://github.com/Miffyli/ToriLLE/tree/master/experiments/stable_baselines_experiments). Again, it is not the original code used with the publication partly due to modifications in `stable-baselines`, but it has the same (hardcoded) hyperparameters.

**Comment by Omegastick** [comment]
Great, thanks. I'm having a read now.
